### ISSUE TITLE
Add "generate tiles" utility

### ISSUE THREAD

**Issue by nikmolnar** [consbio/seedsource-core#16]
For now, this should accept a seedzone set (identified by the `source` field on the `SeedZone` model), and create vector tiles from this.

One approach, would be to use this Python library for creating vector tiles: https://github.com/tilezen/mapbox-vector-tile

Another approach would be do dump seedzones to GeoJSON and use tippecanoe to convert: https://github.com/mapbox/tippecanoe

Resulting `mbtiles` files need to be served by [mbtileserver](https://github.com/consbio/mbtileserver) ~~Nginx (in production; or Django debug server in development)~~. Modifying the map in the UI to handle vector tiles will be addressed in a separate issue.

**Comment by brendan-ward** [comment]
@nikmolnar why not serve the tiles with `mbtileserver`?

**Comment by nikmolnar** [comment]
That's the plan. This issue is for _creating_ the tiles.

**Comment by nikmolnar** [comment]
Ah, I see I said the files would be served by Nginx. That's incorrect.

**Comment by nikmolnar** [comment]
@klinkow Please note: mbtiles files will _not_ be served by Nginx. They will be served using [mbtileserver](https://github.com/consbio/mbtileserver). They _will_ still be proxied through Nginx though. Let's discuss when you get to this.
