### ISSUE TITLE
Consume vector tiles layers from Leaflet map

### ISSUE THREAD

**Issue by nikmolnar** [consbio/seedsource-core#17]
Update the leaflet map to be able to display arbitrary vector tiles layers

**Comment by brendan-ward** [comment]
We've had success with [`Leaflet.VectorGrid`](https://github.com/Leaflet/Leaflet.VectorGrid) in other projects, though performance is proportional to complexity of the vector tiles.

Beware multi-part features though; as of last time I checked this has not been fixed.  I have a long-standing PR (https://github.com/Leaflet/Leaflet.VectorGrid/pull/132) that has gotten no attention rom the maintainers, but if you need this functionality you can use my fork for now.
