### ISSUE TITLE
Sidebar Tabs

### ISSUE THREAD

**Issue by klinkow** [consbio/seedsource-core#6]
In tablet only screen size, the tabs from the side bar stretch across the whole screen.

**Comment by nikmolnar** [comment]
Only in profile mode, where this is desired behavior.

<img width="366" alt="screen shot 2018-05-10 at 5 32 33 pm" src="https://user-images.githubusercontent.com/2422416/39900666-31bef324-5478-11e8-8d56-6dc6aecd1cb5.png">

<img width="515" alt="screen shot 2018-05-10 at 5 32 43 pm" src="https://user-images.githubusercontent.com/2422416/39900668-360ebbda-5478-11e8-94bb-23e096f60970.png">

**Comment by nikmolnar** [comment]
The reason we do this is that the size left for the map would be too small to be useful. Therefore, we expand the tabs to full width.

**Comment by klinkow** [comment]
![screenshot from 2018-05-10 17-39-33](https://user-images.githubusercontent.com/20808982/39900807-3bb412d2-5479-11e8-948c-0dc5169bd85b.png)

**Comment by nikmolnar** [comment]
Ah ha! Nice fine. Thanks for providing the screenshot.
